// Common Action Types
export const FETCH_MAD_CSV_SUCCESS = 'FETCH_MAD_CSV_SUCCESS';
export const FETCH_ASI_CSV_SUCCESS = 'FETCH_ASI_CSV_SUCCESS';
export const FETCH_BDW_CSV_SUCCESS = 'FETCH_BDW_CSV_SUCCESS';
export const FETCH_MAD_SUCCESS = 'FETCH_MAD_SUCCESS';
export const FETCH_ASI_SUCCESS = 'FETCH_ASI_SUCCESS';
export const FETCH_BDW_SUCCESS = 'FETCH_BDW_SUCCESS';
export const FETCH_PMA_SUCCESS = 'FETCH_PMA_SUCCESS';

//Executive Dashboard Normal Action Types
export const FETCH_EXEC_CHANNEL_SUCCESS = 'FETCH_EXEC_CHANNEL_SUCCESS';
export const FETCH_EXEC_PRODUCT_SUCCESS = 'FETCH_EXEC_PRODUCT_SUCCESS';
export const FETCH_EXEC_DSA_SUCCESS = 'FETCH_EXEC_DSA_SUCCESS';
export const FETCH_EXEC_PROD_PAY_SUCCESS = 'FETCH_EXEC_PROD_PAY_SUCCESS';
export const FETCH_EXEC_PROD_PRODUCT_SUCCESS = 'FETCH_EXEC_PROD_PRODUCT_SUCCESS';
export const FETCH_EXEC_DEMOGRAPHICS_SUCCESS = 'FETCH_EXEC_DEMOGRAPHICS_SUCCESS';
export const FETCH_EXEC_CSR_SUCCESS = 'FETCH_EXEC_CSR_SUCCESS';

//Executive Dashboard CSV Action Types
export const FETCH_EXEC_CHANNEL_CSV_SUCCESS = 'FETCH_EXEC_CHANNEL_CSV_SUCCESS';
export const FETCH_EXEC_PRODUCT_CSV_SUCCESS = 'FETCH_EXEC_PRODUCT_CSV_SUCCESS';
export const FETCH_EXEC_DSA_CSV_SUCCESS = 'FETCH_EXEC_DSA_CSV_SUCCESS';
export const FETCH_DEMOGRAPHICS_CSV_SUCCESS = 'FETCH_DEMOGRAPHICS_CSV_SUCCESS';
export const FETCH_EXEC_PROD_PAY_CSV_SUCCESS = 'FETCH_EXEC_PROD_PAY_CSV_SUCCESS';
export const FETCH_EXEC_PROD_PRODUCT_CSV_SUCCESS = 'FETCH_EXEC_PROD_PRODUCT_CSV_SUCCESS';

//Sub Dashboard Normal Action Types
export const FETCH_SUB_CHANNAL_SUCCESS = 'FETCH_SUB_CHANNAL_SUCCESS';
export const FETCH_SUB_PRODUCT_SUCCESS = 'FETCH_SUB_PRODUCT_SUCCESS';
export const FETCH_SUB_DSA_SUCCESS = 'FETCH_SUB_DSA_SUCCESS';
export const FETCH_SUB_PROD_PAY_SUCCESS = 'FETCH_SUB_PROD_PAY_SUCCESS';
export const FETCH_SUB_PROD_PRODUCT_SUCCESS = 'FETCH_SUB_PROD_PRODUCT_SUCCESS';

 //Sub-Dashboard CSV Action Types
export const FETCH_SUB_CHANNEL_CSV_SUCCESS = 'FETCH_SUB_CHANNEL_CSV_SUCCESS';
export const FETCH_SUB_PRODUCT_CSV_SUCCESS = 'FETCH_SUB_PRODUCT_CSV_SUCCESS';
export const FETCH_SUB_DSA_CSV_SUCCESS = 'FETCH_SUB_DSA_CSV_SUCCESS';
export const FETCH_SUB_PROD_PAY_CSV_SUCCESS = 'FETCH_SUB_PROD_PAY_CSV_SUCCESS';
export const FETCH_SUB_PROD_PRODUCT_CSV_SUCCESS = 'FETCH_SUB_PROD_PRODUCT_CSV_SUCCESS';

//Sub Dashboard Recommender Action Types
export const FETCH_SUB_CHANNEL_RECOMMENDER_SUCCESS = 'FETCH_SUB_CHANNEL_RECOMMENDER_SUCCESS';
export const FETCH_SUB_PRODUCT_RECOMMENDER_SUCCESS = 'FETCH_SUB_PRODUCT_RECOMMENDER_SUCCESS';
export const FETCH_SUB_DSA_RECOMMENDER_SUCCESS = 'FETCH_SUB_DSA_RECOMMENDER_SUCCESS';
export const FETCH_SUB_PROD_PAY_RECOMMENDER_SUCCESS = 'FETCH_SUB_PROD_PAY_RECOMMENDER_SUCCESS';
export const FETCH_SUB_PROD_PRODUCT_RECOMMENDER_SUCCESS = 'FETCH_SUB_PROD_PRODUCT_RECOMMENDER_SUCCESS';

 //Client Data Loader Action Types
export const FETCH_DATA_LOADER_SUCCESS = 'FETCH_DATA_LOADER_SUCCESS';

//Data Browser Action Types
export const FETCH_DEFAULT_DATA_BROWSER_SUCCESS = 'FETCH_DEFAULT_DATA_BROWSER_SUCCESS';
export const FETCH_SELECTED_DATA_BROWSER_SUCCESS = 'FETCH_SELECTED_DATA_BROWSER_SUCCESS';

//Filter Metadata Action Types
export const FETCH_FILTER_METADATA_SUCCESS = 'FETCH_FILTER_METADATA_SUCCESS';
export const FETCH_SELECTED_KEYS_SUCCESS = 'FETCH_SELECTED_KEYS_SUCCESS';
export const FETCH_DEFAULT_KEYS_SUCCESS = 'FETCH_DEFAULT_KEYS_SUCCESS';

// Auth Action Types(Login, Signup, Admin Login, QueueEmail)
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
export const FETCH_ADMIN_LOGIN_SUCCESS = 'FETCH_ADMIN_LOGIN_SUCCESS';
export const FETCH_ADMIN_LOGOUT_SUCCESS = 'FETCH_ADMIN_LOGOUT_SUCCESS';
export const FETCH_QUEUE_EMAIL_SUCCESS = 'FETCH_QUEUE_EMAIL_SUCCESS';
export const FETCH_PENDING_EMAIL_SUCCESS = 'FETCH_PENDING_EMAIL_SUCCESS';
export const FETCH_EMAIL_PREREGISTER_SUCCESS = 'FETCH_EMAIL_PREREGISTER_SUCCESS';